-- ntosbe.codegen — small generated-file targets that gate specific
-- nmake builds.  All four wrap a fixed-shape "if output is missing or
-- input newer, run a tool" recipe.
--
--   ensure_error_h   ntosbe.generr      → NTOS/RTL/error.h
--   ensure_bugcodes  mc BUGCODES.MC   → NTOS/INC/bugcodes.h, INIT/bugcodes.rc
--   ensure_serlog    mc SERLOG.MC     → DD/SERIAL/serlog.h, /serlog.rc
--   geni386          cl386 + link + run → SDK/INC/KS386.INC, NTOS/INC/HAL386.INC
--
-- Each returns true on success, false on failure (and platform.log's
-- the reason).  All path I/O routes through ntosbe.platform; tool
-- spawning routes through ntosbe.tchain — so this module is platform-
-- neutral and works unchanged inside MicroNT once the in-OS spawn
-- backend lands.
--
-- configure{ nt_root, src_root } binds the two roots:
--   nt_root  - absolute path to NT/    (SDK headers, NLS sources)
--   src_root - absolute path to src/   (host-tool spawn cwd for geni386)

local platform  = require('ntosbe.platform')
local toolchain = require('ntosbe.tchain')

local M = {}

local cfg

function M.configure(opts)
    cfg = {
        nt_root  = assert(opts.nt_root,  "configure: nt_root required"),
        src_root = assert(opts.src_root, "configure: src_root required"),
    }
    cfg.ntos = cfg.nt_root .. "/PRIVATE/NTOS"
end

-- ----------------------------------------------------------------
-- Common helpers.
-- ----------------------------------------------------------------

local function newer_than(a, b)
    local am, bm = platform.mtime(a), platform.mtime(b)
    return am and bm and am > bm
end

local function copy_if_present(src, dst)
    if platform.file_exists(src) then platform.copy_file(src, dst) end
end

-- ----------------------------------------------------------------
-- ensure_error_h — wraps ntosbe.generr (pure Lua port of the stock
-- NT generr.exe).  Loaded as a regular pkg module via require, so
-- the same code path works on host and inside MicroNT — no need to
-- ship src/tools/ as a special case.
-- ----------------------------------------------------------------

function M.ensure_error_h()
    local generr  = require('ntosbe.generr')
    local ok, err = pcall(generr.run, cfg.nt_root,
                          cfg.ntos .. "/RTL/error.h")
    if not ok then
        platform.log("GENERR: " .. tostring(err))
        return false
    end
    return true
end

-- ----------------------------------------------------------------
-- ensure_bugcodes — bugcodes.rc / bugcodes.h are generated by mc.exe
-- from NLS/BUGCODES.MC.  ntoskrnl.rc #includes bugcodes.rc; many
-- public headers reference bugcodes.h.
-- ----------------------------------------------------------------

function M.ensure_bugcodes()
    local nls = cfg.ntos .. "/NLS"
    if platform.file_exists(nls .. "/bugcodes.rc")
       and platform.file_exists(cfg.ntos .. "/INC/bugcodes.h")
       and newer_than(nls .. "/bugcodes.rc", nls .. "/BUGCODES.MC") then
        return true
    end
    platform.log(">>> mc bugcodes.mc -> bugcodes.h/.rc")
    if toolchain.run_wibo_tool(nls, "mc", "BUGCODES.MC") ~= 0 then
        platform.log("!!! mc on BUGCODES.MC failed")
        return false
    end
    -- mc.exe emits case-matching names on Windows; normalise for our
    -- case-sensitive Linux FS.
    copy_if_present(nls .. "/BUGCODES.rc",  cfg.ntos .. "/INIT/bugcodes.rc")
    copy_if_present(nls .. "/BUGCODES.h",   cfg.ntos .. "/INC/bugcodes.h")
    copy_if_present(nls .. "/MSG00001.bin", cfg.ntos .. "/INIT/msg00001.bin")
    return true
end

-- ----------------------------------------------------------------
-- ensure_serlog — serial.sys's SERLOG.MC compiled to serlog.rc/.h
-- before the SERIAL build.
-- ----------------------------------------------------------------

function M.ensure_serlog()
    local dir = cfg.ntos .. "/DD/SERIAL"
    if platform.file_exists(dir .. "/serlog.rc")
       and platform.file_exists(dir .. "/serlog.h")
       and newer_than(dir .. "/serlog.rc", dir .. "/SERLOG.MC") then
        return true
    end
    platform.log(">>> mc SERLOG.MC -> serlog.h/.rc")
    if toolchain.run_wibo_tool(dir, "mc", "SERLOG.MC") ~= 0 then
        platform.log("!!! mc on SERLOG.MC failed")
        return false
    end
    copy_if_present(dir .. "/SERLOG.rc", dir .. "/serlog.rc")
    copy_if_present(dir .. "/SERLOG.h",  dir .. "/serlog.h")
    return true
end

-- ----------------------------------------------------------------
-- ensure_cmdmsg — cmd.exe's CMDMSG.MC compiled to cmdmsg.rc/.h +
-- msg00001.bin before the CMD build.  Same shape as ensure_bugcodes:
-- the .mc emits CASE.h / CASE.rc on Windows, we lowercase the copies
-- so cmd.h's `#include "cmdmsg.h"` and cmd.rc's `RCINCLUDE cmdmsg.rc`
-- find them on a case-sensitive Linux FS.
-- ----------------------------------------------------------------

function M.ensure_cmdmsg()
    local dir = cfg.nt_root .. "/PRIVATE/WINDOWS/CMD"
    if platform.file_exists(dir .. "/cmdmsg.rc")
       and platform.file_exists(dir .. "/cmdmsg.h")
       and newer_than(dir .. "/cmdmsg.rc", dir .. "/CMDMSG.MC") then
        return true
    end
    platform.log(">>> mc CMDMSG.MC -> cmdmsg.h/.rc")
    if toolchain.run_wibo_tool(dir, "mc", "CMDMSG.MC") ~= 0 then
        platform.log("!!! mc on CMDMSG.MC failed")
        return false
    end
    copy_if_present(dir .. "/CMDMSG.rc",   dir .. "/cmdmsg.rc")
    copy_if_present(dir .. "/CMDMSG.h",    dir .. "/cmdmsg.h")
    return true
end

-- ----------------------------------------------------------------
-- geni386 — host-side struct offset generator.  Compiles
-- KE/I386/GENI386.C, links against LIBC + KERNEL32, and runs the
-- resulting EXE to spit out KS386.INC + HAL386.INC, which assembly
-- code in KE/I386 and the HAL build pull in via $(386_OBJECTS).
--
-- Returns 0 on success / non-zero rc on failure, mirroring the rest
-- of the target API in build.lua.
-- ----------------------------------------------------------------

function M.geni386()
    platform.log("========================================")
    platform.log("Building: GENI386 (struct offset generator)")
    platform.log("========================================")

    local nt_root_win  = toolchain.path_to_win(cfg.nt_root)
    local geni_src     = cfg.nt_root .. "/PRIVATE/NTOS/KE/I386/GENI386.C"
    local geni_dir     = cfg.ntos .. "/INIT/UP/obj/i386"
    platform.mkdir_p(geni_dir)
    local geni_dir_win = toolchain.path_to_win(geni_dir)

    if not platform.file_exists(geni_src) then
        platform.log("ERROR: GENI386.C not found")
        return 1
    end

    local cl_args = {
        "-nologo", "-c", "-Zp8", "-Gz", "-Di386=1", "-D_X86_=1", "-DNT_UP=1",
        "-DSTD_CALL", "-DCONDITION_HANDLING=1", "-DWIN32_LEAN_AND_MEAN=1",
        "-D_NTSYSTEM_", "-DDBG=0", "-DDEVL=1",
        "-I" .. nt_root_win .. "\\PRIVATE\\NTOS\\INC",
        "-I" .. nt_root_win .. "\\PRIVATE\\NTOS\\KE",
        "-I" .. nt_root_win .. "\\PRIVATE\\INC",
        "-I" .. nt_root_win .. "\\PUBLIC\\OAK\\INC",
        "-I" .. nt_root_win .. "\\PUBLIC\\SDK\\INC",
        "-I" .. nt_root_win .. "\\PUBLIC\\SDK\\INC\\CRT",
        nt_root_win .. "\\PRIVATE\\NTOS\\KE\\I386\\GENI386.C",
        "-Fo" .. geni_dir_win .. "\\geni386.obj",
    }
    if toolchain.run_wibo_tool(cfg.src_root, "cl386", unpack(cl_args)) ~= 0 then
        return 1
    end

    local link_args = {
        "-nologo", "-subsystem:console",
        "-out:" .. geni_dir_win .. "\\geni386.exe",
        geni_dir_win .. "\\geni386.obj",
        nt_root_win .. "\\PUBLIC\\SDK\\LIB\\I386\\LIBC.LIB",
        nt_root_win .. "\\PUBLIC\\SDK\\LIB\\I386\\kernel32.lib",
    }
    if toolchain.run_wibo_tool(cfg.src_root, "link", unpack(link_args)) ~= 0 then
        return 1
    end

    -- The just-built geni386.exe lives outside wibo-tools; invoke by
    -- absolute host path through the toolchain bridge.
    if toolchain.wibo_spawn_args(cfg.src_root, geni_dir .. "/geni386.exe", {
        nt_root_win .. "\\PUBLIC\\SDK\\INC\\KS386.INC",
        nt_root_win .. "\\PRIVATE\\NTOS\\INC\\HAL386.INC",
    }) ~= 0 then return 1 end

    platform.log(">>> GENI386: KS386.INC and HAL386.INC regenerated")
    return 0
end

return M
