/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1991  Microsoft Corporation

Module Name:

    cmdmsg.h

Abstract:

    This file contains the message definitions for the Win32 CMD.EXE
    program.

Author:

    Steve Wood (stevewo) 25-Jan-1991

Revision History:

Notes:

    This file is generated by the MC tool from the winerror.msg file.

--*/

#ifndef _CMDMSG_
#define _CMDMSG_


//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: MSG_RESPONSE_DATA
//
// MessageText:
//
//  Y N A R I
//
#define MSG_RESPONSE_DATA                0x00002328L

//
// MessageId: MSG_BAD_PARM1
//
// MessageText:
//
//  An incorrect parameter was
//  entered for the command.
//
#define MSG_BAD_PARM1                    0x00002329L

//
// MessageId: MSG_BAD_SYNTAX
//
// MessageText:
//
//  The syntax of the command is incorrect.
//
#define MSG_BAD_SYNTAX                   0x0000232AL

//
// MessageId: MSG_STRIKE_ANY_KEY
//
// MessageText:
//
//  Press any key to continue . . . %0
//
#define MSG_STRIKE_ANY_KEY               0x0000232BL

//
// MessageId: MSG_CMD_DELETE
//
// MessageText:
//
//  %1, Delete (Y/N)? %0
//
#define MSG_CMD_DELETE                   0x0000232CL

//
// MessageId: MSG_COM_SEARCH_DIR_BAD
//
// MessageText:
//
//  The system cannot find the
//  command processor in the path specified.
//
#define MSG_COM_SEARCH_DIR_BAD           0x0000232DL

//
// MessageId: MSG_REN_INVAL_PATH_FILENAME
//
// MessageText:
//
//  The system cannot accept the path
//  or file name requested.
//
#define MSG_REN_INVAL_PATH_FILENAME      0x0000232EL

//
// MessageId: MSG_INVALID_DATE
//
// MessageText:
//
//  The system cannot accept the date entered.
//
#define MSG_INVALID_DATE                 0x0000232FL

//
// MessageId: MSG_NO_BAT_LABEL
//
// MessageText:
//
//  The system cannot find the batch label specified.
//
#define MSG_NO_BAT_LABEL                 0x00002330L

//
// MessageId: MSG_DIR_BAD_COMMAND_OR_FILE
//
// MessageText:
//
//  The name specified is not recognized as an
//  internal or external command, operable program or batch file.
//
#define MSG_DIR_BAD_COMMAND_OR_FILE      0x00002331L

//
// MessageId: MSG_REN_INVALID_TIME
//
// MessageText:
//
//  The system cannot accept the time entered.
//
#define MSG_REN_INVALID_TIME             0x00002332L

//
// MessageId: MSG_BAD_DOS_VER
//
// MessageText:
//
//  The application program is not compatible
//  with the version of the operating system being used.
//
#define MSG_BAD_DOS_VER                  0x00002333L

//
// MessageId: MSG_COMM_VER
//
// MessageText:
//
//  Microsoft(R) Windows NT(TM)
//  (C) Copyright 1985-1994 Microsoft Corp.
//
#define MSG_COMM_VER                     0x00002334L

//
// MessageId: MSG_C
//
// MessageText:
//
//  ^C
//
#define MSG_C                            0x00002335L

//
// MessageId: MSG_FILES_COPIED
//
// MessageText:
//
//  %1 file(s) copied.
//
#define MSG_FILES_COPIED                 0x00002336L

//
// MessageId: MSG_CURRENT_DATE
//
// MessageText:
//
//  The current date is: %0
//
#define MSG_CURRENT_DATE                 0x00002337L

//
// MessageId: MSG_CURRENT_TIME
//
// MessageText:
//
//  The current time is: %0
//
#define MSG_CURRENT_TIME                 0x00002338L

//
// MessageId: MSG_DIR_OF
//
// MessageText:
//
//   Directory of %1
//  
//
#define MSG_DIR_OF                       0x00002339L

//
// MessageId: MSG_OUT_OF_ENVIRON_SPACE
//
// MessageText:
//
//  The system is out of environment space.
//
#define MSG_OUT_OF_ENVIRON_SPACE         0x0000233AL

//
// MessageId: MSG_INVALID_DOS_FILENAME
//
// MessageText:
//
//   The file name entered is not valid in DOS mode.
//
#define MSG_INVALID_DOS_FILENAME         0x0000233BL

//
// MessageId: MSG_EXEC_FAILURE
//
// MessageText:
//
//  The system cannot execute the specified program.
//
#define MSG_EXEC_FAILURE                 0x0000233CL

//
// MessageId: MSG_FILES_FREE
//
// MessageText:
//
//       %1 File(s)   %2 bytes free
//
#define MSG_FILES_FREE                   0x0000233DL

//
// MessageId: MSG_FILES_ONLY
//
// MessageText:
//
//       %1 File(s).
//
#define MSG_FILES_ONLY                   0x0000233EL

//
// MessageId: MSG_LINES_TOO_LONG
//
// MessageText:
//
//  The input line is too long.
//
#define MSG_LINES_TOO_LONG               0x0000233FL

//
// MessageId: MSG_CONT_LOST_BEF_COPY
//
// MessageText:
//
//  The contents of the target file
//  were lost.
//
#define MSG_CONT_LOST_BEF_COPY           0x00002340L

//
// MessageId: MSG_INSRT_DISK_BAT
//
// MessageText:
//
//  Insert the diskette that contains the batch file
//  and press any key when ready. %0
//
#define MSG_INSRT_DISK_BAT               0x00002341L

//
// MessageId: MSG_ENTER_NEW_DATE
//
// MessageText:
//
//  Enter the new date: (mm-dd-yy) %0
//
#define MSG_ENTER_NEW_DATE               0x00002342L

//
// MessageId: MSG_ENTER_NEW_TIME
//
// MessageText:
//
//  Enter the new time: %0
//
#define MSG_ENTER_NEW_TIME               0x00002343L

//
// MessageId: MSG_RDR_HNDL_CREATE
//
// MessageText:
//
//  The handle could not be duplicated
//  during redirection of handle %1.
//
#define MSG_RDR_HNDL_CREATE              0x00002344L

//
// MessageId: MSG_ECHO_OFF
//
// MessageText:
//
//  ECHO is off.
//
#define MSG_ECHO_OFF                     0x00002345L

//
// MessageId: MSG_ECHO_ON
//
// MessageText:
//
//  ECHO is on.
//
#define MSG_ECHO_ON                      0x00002346L

//
// MessageId: MSG_VERIFY_OFF
//
// MessageText:
//
//  VERIFY is off.
//
#define MSG_VERIFY_OFF                   0x00002347L

//
// MessageId: MSG_VERIFY_ON
//
// MessageText:
//
//  VERIFY is on.
//
#define MSG_VERIFY_ON                    0x00002348L

//
// MessageId: MSG_CANNOT_COPIED_ONTO_SELF
//
// MessageText:
//
//  The file cannot be copied onto itself.
//
#define MSG_CANNOT_COPIED_ONTO_SELF      0x00002349L

//
// MessageId: MSG_SYNERR_GENL
//
// MessageText:
//
//  %1 was unexpected at this time.
//
#define MSG_SYNERR_GENL                  0x0000234AL

//
// MessageId: MSG_TOP_LEVEL_PROCESS_CAN
//
// MessageText:
//
//  CMD.EXE has halted. %0
//
#define MSG_TOP_LEVEL_PROCESS_CAN        0x0000234BL

//
// MessageId: MSG_PID_IS
//
// MessageText:
//
//  The Process Identification Number is %1.
//
#define MSG_PID_IS                       0x0000234CL

//
// MessageId: MSG_DUP_FILENAME_OR_NOT_FD
//
// MessageText:
//
//  A duplicate file name exists, or the file
//  cannot be found.
//
#define MSG_DUP_FILENAME_OR_NOT_FD       0x0000234DL

//
// MessageId: MSG_ARE_YOU_SURE
//
// MessageText:
//
//  %1, Are you sure (Y/N)? %0
//
#define MSG_ARE_YOU_SURE                 0x0000234EL

//
// MessageId: MSG_TOKEN_TOO_LONG
//
// MessageText:
//
//  The following character string is too long:
//  %1
//
#define MSG_TOKEN_TOO_LONG               0x0000234FL

//
// MessageId: MSG_MS_DOS_VERSION
//
// MessageText:
//
//  Windows NT Version %1.%2 %0
//
#define MSG_MS_DOS_VERSION               0x00002350L

//
// MessageId: MSG_PIPE_FAILURE
//
// MessageText:
//
//  The handle could not be duplicated during
//  a pipe operation.
//
#define MSG_PIPE_FAILURE                 0x00002351L

//
// MessageId: MSG_MS_MORE
//
// MessageText:
//
//  More? %0
//
#define MSG_MS_MORE                      0x00002352L

//
// MessageId: MSG_REAL_MODE_ONLY
//
// MessageText:
//
//  The system cannot complete the process.
//
#define MSG_REAL_MODE_ONLY               0x00002353L

//
// MessageId: MSG_SUNDAY
//
// MessageText:
//
//  Sun%0
//
#define MSG_SUNDAY                       0x00002354L

//
// MessageId: MSG_MONDAY
//
// MessageText:
//
//  Mon%0
//
#define MSG_MONDAY                       0x00002355L

//
// MessageId: MSG_TUEDAY
//
// MessageText:
//
//  Tue%0
//
#define MSG_TUEDAY                       0x00002356L

//
// MessageId: MSG_WEDDAY
//
// MessageText:
//
//  Wed%0
//
#define MSG_WEDDAY                       0x00002357L

//
// MessageId: MSG_THRDAY
//
// MessageText:
//
//  Thu%0
//
#define MSG_THRDAY                       0x00002358L

//
// MessageId: MSG_FRIDAY
//
// MessageText:
//
//  Fri%0
//
#define MSG_FRIDAY                       0x00002359L

//
// MessageId: MSG_SATDAY
//
// MessageText:
//
//  Sat%0
//
#define MSG_SATDAY                       0x0000235AL

//
// MessageId: MSG_DR_VOL_SERIAL
//
// MessageText:
//
//   Volume Serial Number is %1
//
#define MSG_DR_VOL_SERIAL                0x0000235BL

//
// MessageId: MSG_DIR_EXISTS
//
// MessageText:
//
//  A subdirectory or file %1 already exists.
//
#define MSG_DIR_EXISTS                   0x0000235CL

//
// MessageId: MSG_ERR_PROC_ARG
//
// MessageText:
//
//  Error occurred while processing: %1.
//
#define MSG_ERR_PROC_ARG                 0x0000235DL

//
// MessageId: MSG_HAS_NO_LABEL
//
// MessageText:
//
//   Volume in drive %1 has no label.
//
#define MSG_HAS_NO_LABEL                 0x0000235EL

//
// MessageId: MSG_DR_VOL_LABEL
//
// MessageText:
//
//   Volume in drive %1 is %2
//
#define MSG_DR_VOL_LABEL                 0x0000235FL

//
// MessageId: MSG_KEYS_ON
//
// MessageText:
//
//  KEYS is on.
//
#define MSG_KEYS_ON                      0x00002360L

//
// MessageId: MSG_KEYS_OFF
//
// MessageText:
//
//  KEYS is off.
//
#define MSG_KEYS_OFF                     0x00002361L

//
// MessageId: MSG_START_INVALID_PARAMETER
//
// MessageText:
//
//  The system cannot accept the START command parameter %1.
//
#define MSG_START_INVALID_PARAMETER      0x00002362L

//
// MessageId: MSG_CMD_FILE_NOT_FOUND
//
// MessageText:
//
//  The system cannot find the file %1.
//
#define MSG_CMD_FILE_NOT_FOUND           0x00002363L

//
// MessageId: MSG_CMD_INVAL_PIPE
//
// MessageText:
//
//  The process tried to write to a nonexistent pipe.
//
#define MSG_CMD_INVAL_PIPE               0x00002364L

//
// MessageId: MSG_CMD_CANT_FRGRND
//
// MessageText:
//
//  The system cannot start the session in the foreground.
//
#define MSG_CMD_CANT_FRGRND              0x00002365L

//
// MessageId: MSG_CMD_SYS_ERR
//
// MessageText:
//
//  
//  A non-recoverable error occurred.
//  The process ended.
//
#define MSG_CMD_SYS_ERR                  0x00002366L

//
// MessageId: MSG_CMD_DIV_0
//
// MessageText:
//
//  
//  The system detected a divide by zero error.
//
#define MSG_CMD_DIV_0                    0x00002367L

//
// MessageId: MSG_CMD_SOFT_ERR
//
// MessageText:
//
//  
//  The process has stopped.  The software
//  diagnostic code (trap number) is %1.
//
#define MSG_CMD_SOFT_ERR                 0x00002368L

//
// MessageId: MSG_CMD_COPROC
//
// MessageText:
//
//  
//  The process ended when it tried to use
//  a non-existent math processor.
//
#define MSG_CMD_COPROC                   0x00002369L

//
// MessageId: MSG_CMD_KILLED
//
// MessageText:
//
//  The external process was canceled by a Ctrl+Break or another process.
//  
//
#define MSG_CMD_KILLED                   0x0000236AL

//
// MessageId: MSG_CMD_NOT_RECOGNIZED
//
// MessageText:
//
//  "%1" is not a recognized device.
//
#define MSG_CMD_NOT_RECOGNIZED           0x0000236BL

//
// MessageId: MSG_CMD_BATCH_FILE_MISSING
//
// MessageText:
//
//  The batch file cannot be found.
//
#define MSG_CMD_BATCH_FILE_MISSING       0x0000236CL

//
// MessageId: MSG_FILES_MOVED
//
// MessageText:
//
//  %1 file(s) moved.
//
#define MSG_FILES_MOVED                  0x0000236EL

//
// MessageId: MSG_TRAPC
//
// MessageText:
//
//  A program attempted to reference storage outside the
//  limits of a stack segment.  The program was ended.
//  
//  %1
//
#define MSG_TRAPC                        0x0000236FL

//
// MessageId: MSG_UNEXPEC_ERROR_ENC
//
// MessageText:
//
//  Error %1 encountered an unexpected end of file
//  on the redirected input. The process has stopped.
//
#define MSG_UNEXPEC_ERROR_ENC            0x00002370L

//
// MessageId: MSG_LITERAL_TEXT
//
// MessageText:
//
//  %1%0
//
#define MSG_LITERAL_TEXT                 0x00002371L

//
// MessageId: MSG_NOT_IMPLEMENTED
//
// MessageText:
//
//  Command not implemented.
//
#define MSG_NOT_IMPLEMENTED              0x00002372L

//
// MessageId: MSG_DIR
//
// MessageText:
//
//  <DIR>       %0
//
#define MSG_DIR                          0x00002373L

//
// MessageId: MSG_NO_MEMORY
//
// MessageText:
//
//  Out of memory.
//
#define MSG_NO_MEMORY                    0x00002374L

//
// MessageId: MSG_INVALID_SWITCH
//
// MessageText:
//
//  Invalid switch - "%1".
//
#define MSG_INVALID_SWITCH               0x00002375L

//
// MessageId: MSG_PARAMETER_FORMAT_NOT_CORRECT
//
// MessageText:
//
//  Parameter format not correct - "%1".
//
#define MSG_PARAMETER_FORMAT_NOT_CORRECT 0x00002376L

//
// MessageId: MSG_ERROR_IN_DIRCMD
//
// MessageText:
//
//  (Error occurred in environment variable)
//
#define MSG_ERROR_IN_DIRCMD              0x00002377L

//
// MessageId: MSG_FILES_COUNT_FREE
//
// MessageText:
//
//       %1 File(s) %2 bytes
//
#define MSG_FILES_COUNT_FREE             0x00002378L

//
// MessageId: MSG_FILES_TOTAL_FREE
//
// MessageText:
//
//                        %1 bytes free
//
#define MSG_FILES_TOTAL_FREE             0x00002379L

//
// MessageId: MSG_FILE_TOTAL
//
// MessageText:
//
//       Total Files Listed:
//
#define MSG_FILE_TOTAL                   0x0000237AL

//
// MessageId: MSG_BATCH_TERM
//
// MessageText:
//
//  Terminate batch job (Y/N)? %0
//
#define MSG_BATCH_TERM                   0x0000237BL

//
// MessageId: MSG_BAD_CURDIR
//
// MessageText:
//
//  The current directory is invalid.
//
#define MSG_BAD_CURDIR                   0x0000237CL

//
// MessageId: MSG_HELP_CHDIR
//
// MessageText:
//
//  Displays the name of or changes the current directory.
//  
//  CHDIR [/D] [drive:][path]
//  CHDIR [..]
//  CD [/D] [drive:][path]
//  CD [..]
//  
//    ..   Specifies that you want to change to the parent directory.
//  
//  Type CD drive: to display the current directory in the specified drive.
//  Type CD without parameters to display the current drive and directory.
//  
//  Use the /D switch to change current drive in addition to changing current
//  directory for a drive.
//
#define MSG_HELP_CHDIR                   0x0000237DL

//
// MessageId: MSG_HELP_CLS
//
// MessageText:
//
//  Clears the screen.
//  
//  CLS
//
#define MSG_HELP_CLS                     0x0000237EL

//
// MessageId: MSG_HELP_COPY
//
// MessageText:
//
//  Copies one or more files to another location.
//  
//  COPY [/A | /B] source [/A | /B] [+ source [/A | /B] [+ ...]] [destination
//    [/A | /B]] [/V] [/N]
//  
//    source       Specifies the file or files to be copied.
//    /A           Indicates an ASCII text file.
//    /B           Indicates a binary file.
//    destination  Specifies the directory and/or filename for the new file(s).
//    /V           Verifies that new files are written correctly.
//    /N           Uses short filename, if available, when copying a file with a
//                 non-8dot3 name.
//  
//  To append files, specify a single file for destination, but multiple files
//  for source (using wildcards or file1+file2+file3 format).
//
#define MSG_HELP_COPY                    0x0000237FL

//
// MessageId: MSG_HELP_DATE
//
// MessageText:
//
//  Displays or sets the date.
//  
//  DATE [date]
//  
//  Type DATE without parameters to display the current date setting and
//  a prompt for a new one.  Press ENTER to keep the same date.
//
#define MSG_HELP_DATE                    0x00002380L

//
// MessageId: MSG_HELP_DEL_ERASE
//
// MessageText:
//
//  Deletes one or more files.
//  
//  DEL [/P] [/F] [/S] [/Q] [/A[[:]attributes]] [[drive:][path]filename
//  ERASE [/P] [/F] [/S] [/Q] [/A[[:]attributes]] [[drive:][path]filename
//  
//    [drive:][path]filename
//                  Specifies the file(s) to delete.  Specify multiple
//                  files by using wildcards.
//    /P            Prompts for confirmation before deleting each file.
//    /F            Force deleting of read-only files.
//    /S            Delete specified files from all subdirectories.
//    /Q            Quiet mode, do not ask if ok to delete on global wildcard
//    /A            Selects files to delete based on attributes
//    attributes    R  Read-only files            S  System files
//                  H  Hidden files               A  Files ready for archiving
//                  -  Prefix meaning not
//
#define MSG_HELP_DEL_ERASE               0x00002381L

//
// MessageId: MSG_HELP_DIR
//
// MessageText:
//
//  Displays a list of files and subdirectories in a directory.
//  
//  DIR [drive:][path][filename] [/P] [/W] [/D] [/A[[:]attributes]]
//    [/O[[:]sortorder]] [/T[[:]timefield]] [/S] [/B] [/L] [/N] [/X] [/C]
//  
//    [drive:][path][filename]
//                Specifies drive, directory, and/or files to list.
//  
//    /P          Pauses after each screenful of information.
//    /W          Uses wide list format.
//    /D          Same as wide but files are list sorted by column.
//    /A          Displays files with specified attributes.
//    attributes   D  Directories                R  Read-only files
//                 H  Hidden files               A  Files ready for archiving
//                 S  System files               -  Prefix meaning not
//    /O          List by files in sorted order.
//    sortorder    N  By name (alphabetic)       S  By size (smallest first)
//                 E  By extension (alphabetic)  D  By date & time (earliest first)
//                 G  Group directories first    -  Prefix to reverse order
//    /T          Controls which time field displayed or used for sorting
//    timefield   C  Creation
//                A  Last Access
//                W  Last Written
//    /S          Displays files in specified directory and all subdirectories.
//    /B          Uses bare format (no heading information or summary).
//    /L          Uses lowercase.
//    /N          New long list format where filenames are on the far right.
//    /X          This displays the short names generated for non-8dot3 file
//                names.  The format is that of /N with the short name inserted
//                before the long name. If no short name is present, blanks are
//                displayed in its place.
//    /C          Display the thousand separator in file sizes.  This is the
//                default.  Use /-C to disable display of separator.
//  
//  Switches may be preset in the DIRCMD environment variable.  Override
//  preset switches by prefixing any switch with - (hyphen)--for example, /-W.
//
#define MSG_HELP_DIR                     0x00002382L

//
// MessageId: MSG_HELP_EXIT
//
// MessageText:
//
//  Quits the CMD.EXE program (command interpreter).
//  
//  EXIT
//
#define MSG_HELP_EXIT                    0x00002383L

//
// MessageId: MSG_HELP_MKDIR
//
// MessageText:
//
//  Creates a directory.
//  
//  MKDIR [drive:]path
//  MD [drive:]path
//
#define MSG_HELP_MKDIR                   0x00002384L

//
// MessageId: MSG_HELP_PATH
//
// MessageText:
//
//  Displays or sets a search path for executable files.
//  
//  PATH [[drive:]path[;...][;%%PATH%%]
//  PATH ;
//  
//  Type PATH ; to clear all search-path settings and direct cmd.exe to search
//  only in the current directory.
//  Type PATH without parameters to display the current path.
//  Including %%PATH%% in the new path setting causes the old path to be appended
//  to the new setting.
//
#define MSG_HELP_PATH                    0x00002385L

//
// MessageId: MSG_HELP_PROMPT
//
// MessageText:
//
//  Changes the cmd.exe command prompt.
//  
//  PROMPT [text]
//  
//    text    Specifies a new command prompt.
//  
//  Prompt can be made up of normal characters and the following special codes:
//  
//    $A   & (Ampersand)
//    $B   | (pipe)
//    $C   ( (Left parenthesis)
//    $D   Current date
//    $E   Escape code (ASCII code 27)
//    $F   ) (Right parenthesis)
//    $G   > (greater-than sign)
//    $H   Backspace (erases previous character)
//    $L   < (less-than sign)
//    $N   Current drive
//    $P   Current drive and path
//    $Q   = (equal sign)
//    $S     (space)
//    $T   Current time
//    $V   Windows NT version number
//    $_   Carriage return and linefeed
//    $$   $ (dollar sign)
//  
//  
//
#define MSG_HELP_PROMPT                  0x00002386L

//
// MessageId: MSG_HELP_RMDIR
//
// MessageText:
//
//  Removes (deletes) a directory.
//  
//  RMDIR [/S] [drive:]path
//  RD [/S] [drive:]path
//  
//      /S      Removes all directories and files in the specified directory
//              in addition to the directory itself.  Used to remove a directory
//              tree.
//
#define MSG_HELP_RMDIR                   0x00002387L

//
// MessageId: MSG_HELP_RENAME
//
// MessageText:
//
//  Renames a file or files.
//  
//  RENAME [drive:][path]filename1 filename2.
//  REN [drive:][path]filename1 filename2.
//  
//  Note that you cannot specify a new drive or path for your destination file.
//
#define MSG_HELP_RENAME                  0x00002388L

//
// MessageId: MSG_HELP_SET
//
// MessageText:
//
//  Displays, sets, or removes cmd.exe environment variables.
//  
//  SET [variable=[string]]
//  
//    variable  Specifies the environment-variable name.
//    string    Specifies a series of characters to assign to the variable.
//  
//  Type SET without parameters to display the current environment variables.
//
#define MSG_HELP_SET                     0x00002389L

//
// MessageId: MSG_HELP_TIME
//
// MessageText:
//
//  Displays or sets the system time.
//  
//  TIME [time]
//  
//  Type TIME with no parameters to display the current time setting and a prompt
//  for a new one.  Press ENTER to keep the same time.
//
#define MSG_HELP_TIME                    0x0000238AL

//
// MessageId: MSG_HELP_TYPE
//
// MessageText:
//
//  Displays the contents of a text file or files.
//  
//  TYPE [drive:][path]filename
//
#define MSG_HELP_TYPE                    0x0000238BL

//
// MessageId: MSG_HELP_VER
//
// MessageText:
//
//  Displays the Windows NT version.
//  
//  VER
//
#define MSG_HELP_VER                     0x0000238CL

//
// MessageId: MSG_HELP_VERIFY
//
// MessageText:
//
//  Tells cmd.exe whether to verify that your files are written correctly to a
//  disk.
//  
//  VERIFY [ON | OFF]
//  
//  Type VERIFY without a parameter to display the current VERIFY setting.
//
#define MSG_HELP_VERIFY                  0x0000238DL

//
// MessageId: MSG_HELP_VOL
//
// MessageText:
//
//  Displays the disk volume label and serial number, if they exist.
//  
//  VOL [drive:]
//
#define MSG_HELP_VOL                     0x0000238EL

//
// MessageId: MSG_HELP_CALL
//
// MessageText:
//
//  Calls one batch program from another.
//  
//  CALL [drive:][path]filename [batch-parameters]
//  
//    batch-parameters   Specifies any command-line information required by the
//                       batch program.
//
#define MSG_HELP_CALL                    0x0000238FL

//
// MessageId: MSG_HELP_REM
//
// MessageText:
//
//  Records comments (remarks) in a batch file or CONFIG.SYS.
//  
//  REM [comment]
//
#define MSG_HELP_REM                     0x00002390L

//
// MessageId: MSG_HELP_PAUSE
//
// MessageText:
//
//  Suspends processing of a batch program and displays the message
//      Press any key to continue . . . %0
//  
//  PAUSE
//
#define MSG_HELP_PAUSE                   0x00002391L

//
// MessageId: MSG_HELP_ECHO
//
// MessageText:
//
//  Displays messages, or turns command-echoing on or off.
//  
//    ECHO [ON | OFF]
//    ECHO [message]
//  
//  Type ECHO without parameters to display the current echo setting.
//
#define MSG_HELP_ECHO                    0x00002392L

//
// MessageId: MSG_HELP_GOTO
//
// MessageText:
//
//  Directs cmd.exe to a labeled line in a batch program.
//  
//  GOTO label
//  
//    label   Specifies a text string used in the batch program as a label.
//  
//  You type a label on a line by itself, beginning with a colon.
//
#define MSG_HELP_GOTO                    0x00002393L

//
// MessageId: MSG_HELP_SHIFT
//
// MessageText:
//
//  Changes the position of replaceable parameters in a batch file.
//  
//  SHIFT
//
#define MSG_HELP_SHIFT                   0x00002394L

//
// MessageId: MSG_HELP_IF
//
// MessageText:
//
//  Performs conditional processing in batch programs.
//  
//  IF [NOT] ERRORLEVEL number command
//  IF [NOT] string1==string2 command
//  IF [NOT] EXIST filename command
//  
//    NOT               Specifies that Windows NT should carry out the command only
//                      if the condition is false.
//    ERRORLEVEL number Specifies a true condition if the last program run returned
//                      an exit code equal to or greater than the number specified.
//    command           Specifies the command to carry out if the condition is
//                      met.
//    string1==string2  Specifies a true condition if the specified text strings
//                      match.
//    EXIST filename    Specifies a true condition if the specified filename
//                      exists.
//
#define MSG_HELP_IF                      0x00002395L

//
// MessageId: MSG_HELP_FOR
//
// MessageText:
//
//  Runs a specified command for each file in a set of files.
//  
//  FOR %%variable IN (set) DO command [command-parameters]
//  
//    %%variable Specifies a replaceable parameter.
//    (set)      Specifies a set of one or more files.  Wildcards may be used.
//    command    Specifies the command to carry out for each file.
//    command-parameters
//               Specifies parameters or switches for the specified command.
//  
//  To use the FOR command in a batch program, specify %%%%variable instead of
//  %%variable
//  
//
#define MSG_HELP_FOR                     0x00002396L

//
// MessageId: MSG_HELP_START
//
// MessageText:
//
//  Starts a separate window to run a specified program or command.
//  
//  START ["title"] [/Dpath] [/I] [/MIN] [/MAX] [/SEPARATE]
//        [/LOW | /NORMAL | /HIGH | /REALTIME] [/WAIT] [/B] [command/program] [parameters]
//  
//      "title"     Title to display in  window title bar.
//      path        Starting directory
//      I           The new environment will be the original environment passed
//                  to the cmd.exe and not the current environment.
//      MIN         Start window minimized
//      MAX         Start window maximized
//      SEPARATE    Start 16-bit Windows program in separate memory space
//      LOW         Start application in the IDLE priority class
//      NORMAL      Start application in the NORMAL priority class
//      HIGH        Start application in the HIGH priority class
//      REALTIME    Start application in the REALTIME priority class
//      WAIT        Start application and wait for it to terminate
//      B           Start application without creating a new window. The
//                  application has ^C handling ignored. Unless the application
//                  enables ^C processing, ^Break is the only way to interrupt the
//                  application
//      command/program
//                  If it is an internal cmd command or a batch file then
//                  the command processor is run with the /K switch to cmd.exe.
//                  This means that the window will remain after the command
//                  has been run.
//  
//                  If it is not an internal cmd command or batch file then
//                  it is a program and will run as either a windowed application
//                  or a console application.
//  
//      parameters  These are the parameters passed to the command/program
//  
//
#define MSG_HELP_START                   0x00002397L

//
// MessageId: MSG_HELP_BREAK
//
// MessageText:
//
//  Sets or Clears Extended CTRL+C checking on DOS system
//  
//  This is present for Compatibility with DOS systems. It has no effect
//  under Windows NT.
//
#define MSG_HELP_BREAK                   0x00002398L

//
// MessageId: MSG_HELP_CMD
//
// MessageText:
//
//  Starts a new instance of the Windows/NT command interpreter
//  
//  CMD [[/C | /K] [/Q] string]
//  
//  /C      Carries out the command specified by string and then terminates
//  /K      Carries out the command specified by string but remains
//  /Q      Silently Carries out the command specified by string but remains
//  /A      Causes the output of internal commands to a pipe or file to be ANSI
//  /U      Causes the output of internal commands to a pipe or file to be UNICODE
//  
//  Note that multiple commands separated by the command separator '&&'
//  are accepted for string if surrounded by quotes
//  
//
#define MSG_HELP_CMD                     0x00002399L

//
// MessageId: MSG_TOO_MANY_PARAMETERS
//
// MessageText:
//
//  Too many parameters - %1
//
#define MSG_TOO_MANY_PARAMETERS          0x00002710L

//
// MessageId: MSG_FILE_NOT_FOUND
//
// MessageText:
//
//  File Not Found
//  
//
#define MSG_FILE_NOT_FOUND               0x00002711L

//
// MessageId: MSG_NOT_FOUND
//
// MessageText:
//
//  Could Not Find %1
//  
//
#define MSG_NOT_FOUND                    0x00002712L

//
// MessageId: MSG_TIME_NOT_SUPPORTED
//
// MessageText:
//
//  The FAT File System only support Last Write Times
//
#define MSG_TIME_NOT_SUPPORTED           0x00002713L

//
// MessageId: MSG_HELP_SETLOCAL
//
// MessageText:
//
//  Begins localization of environment changes in a batch file.
//  Environment changes made after SETLOCAL has been issued are
//  local to the batch file.  ENDLOCAL must be issued to
//  restore the previous settings.
//  
//  SETLOCAL
//  
//
#define MSG_HELP_SETLOCAL                0x00002714L

//
// MessageId: MSG_HELP_ENDLOCAL
//
// MessageText:
//
//  Ends localization of environment changes in a batch file.
//  Environment changes made after ENDLOCAL has been issued are
//  not local to the batch file; the previous settings are not
//  restored on termination of the batch file.
//  
//  ENDLOCAL
//  
//
#define MSG_HELP_ENDLOCAL                0x00002715L

//
// MessageId: MSG_HELP_TITLE
//
// MessageText:
//
//  Sets the window title for the command prompt window.
//  
//  TITLE [string]
//  
//    string       Specifies the title for the command prompt window.
//
#define MSG_HELP_TITLE                   0x00002716L

//
// MessageId: MSG_HELP_APPEND
//
// MessageText:
//
//  Allows programs to open data files in specified directories as if they were in
//  the current directory.
//  
//  APPEND [[drive:]path[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]
//  APPEND ;
//  
//    [drive:]path Specifies a drive and directory to append.
//    /X:ON        Applies appended directories to file searches and
//                 application execution.
//    /X:OFF       Applies appended directories only to requests to open files.
//                 /X:OFF is the default setting.
//    /PATH:ON     Applies the appended directories to file requests that already
//                 specify a path.  /PATH:ON is the default setting.
//    /PATH:OFF    Turns off the effect of /PATH:ON.
//    /E           Stores a copy of the appended directory list in an environment
//                 variable named APPEND.  /E may be used only the first time
//                 you use APPEND after starting up your system.
//  
//  Type APPEND ; to clear the appended directory list.
//  Type APPEND without parameters to display the appended directory list.
//  
//
#define MSG_HELP_APPEND                  0x00002717L

//
// MessageId: MSG_HELP_MOVE
//
// MessageText:
//
//  Moves one or more files from one directory to another directory.
//  
//  MOVE [Source] [Target]
//  
//    source       Specifies the path and name of the file(s) to move.
//    target       Specifies the path and name to move file(s) to.
//
#define MSG_HELP_MOVE                    0x00002718L

//
// MessageId: MSG_HELP_PUSHDIR
//
// MessageText:
//
//  Stores the current directory for use by the POPD command, then
//  changes to the specified directory.
//  
//  PUSHD [path | ..]
//  
//    path        Specifies the directory to make the current directory.
//
#define MSG_HELP_PUSHDIR                 0x00002719L

//
// MessageId: MSG_HELP_POPDIR
//
// MessageText:
//
//  Changes to the directory stored by the PUSHD command.
//  
//  POPD
//  
//
#define MSG_HELP_POPDIR                  0x0000271AL

//
// MessageId: MSG_FILE_NAME_PRECEEDING_ERROR
//
// MessageText:
//
//  %1 - %0
//
#define MSG_FILE_NAME_PRECEEDING_ERROR   0x0000271BL

//
// MessageId: MSG_MAX_SETLOCAL
//
// MessageText:
//
//  Maximum setlocal recursion level reached.
//
#define MSG_MAX_SETLOCAL                 0x0000271CL

//
// MessageId: MSG_ENTER_JAPAN_DATE
//
// MessageText:
//
//  Enter the new date: (yy-mm-dd) %0
//
#define MSG_ENTER_JAPAN_DATE             0x0000271DL

//
// MessageId: MSG_ENTER_DEF_DATE
//
// MessageText:
//
//  Enter the new date: (dd-mm-yy) %0
//
#define MSG_ENTER_DEF_DATE               0x0000271EL

#endif // _CMDMSG_
