#!/bin/bash
#
# MicroNT Clean Script
# Removes all build artifacts so build.sh produces a fully clean build
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
NT_ROOT="$SCRIPT_DIR/NT"
NTOS="$NT_ROOT/PRIVATE/NTOS"

echo "Cleaning build artifacts..."

# All obj/ directories under the NT source tree — covers every component's
# build output (.obj, .lib, .res, .exe, .dll, _objects.mac, .def, etc.).
# This replaces a hand-maintained COMP_DIRS list that was always lagging.
find "$NT_ROOT/PRIVATE" -maxdepth 10 -type d -name 'obj' | while read -r d; do
    rm -rf "$d"
    echo "  cleaned ${d#$SCRIPT_DIR/}"
done

# Shared NTOS obj/ (where component .lib files are collected via TARGETPATH)
if [ -d "$NTOS/obj" ]; then
    rm -rf "$NTOS/obj"
    echo "  cleaned NTOS/obj/"
fi

# Shared Windows-subsystem obj/ (baselib.lib / conlib.lib / nlslib.lib
# via TARGETPATH=..\obj or ..\..\obj).
for dir in "$NT_ROOT/PRIVATE/WINDOWS/BASE/obj" "$NT_ROOT/PRIVATE/WINDOWS/obj"; do
    if [ -d "$dir" ]; then
        rm -rf "$dir"
        echo "  cleaned ${dir#$SCRIPT_DIR/}"
    fi
done

# Shared RTL obj/ (rtl.lib via TARGETPATH=..\obj)
if [ -d "$NTOS/RTL/obj" ]; then
    rm -rf "$NTOS/RTL/obj"
    echo "  cleaned NTOS/RTL/obj/"
fi

# MIDL20 lib/ (midl support libs via TARGETPATH=..\lib)
if [ -d "$NT_ROOT/PRIVATE/RPC/MIDL20/lib" ]; then
    rm -rf "$NT_ROOT/PRIVATE/RPC/MIDL20/lib"
    echo "  cleaned RPC/MIDL20/lib/"
fi

# RC temp files (rc.exe leaves R[CD]<letter><5digits> behind on failure)
find "$NT_ROOT/PRIVATE" -maxdepth 10 -name 'R[CD][a-z][0-9][0-9][0-9][0-9][0-9]' -delete 2>/dev/null

# NMAKE temp files (nm<pid>. trailing-dot convention)
find "$NT_ROOT/PRIVATE" -maxdepth 10 -name 'nm[0-9]*' -delete 2>/dev/null

# GDI geni386-generated struct offset file (rebuilt by build_gdi_geni386)
rm -f "$NT_ROOT/PRIVATE/WINDOWS/GDI/INC/GDII386.INC" 2>/dev/null

# mc.exe-generated message resources (rebuilt each time)
rm -f "$NT_ROOT/PRIVATE/WINDOWS/NLSMSG/winerror.h" \
      "$NT_ROOT/PRIVATE/WINDOWS/NLSMSG/winerror.rc" \
      "$NT_ROOT/PRIVATE/WINDOWS/NLSMSG/MSG00001.bin" \
      "$NT_ROOT/PRIVATE/WINDOWS/BASE/CLIENT/winerror.rc" \
      "$NT_ROOT/PRIVATE/WINDOWS/BASE/CLIENT/DAYTONA/MSG00001.bin" 2>/dev/null

# MIDL-generated stubs (rebuilt by build.sh's midl steps)
for stub_dir in \
    "$NT_ROOT/PRIVATE/RPC/RUNTIME/RTIFS" \
    "$NT_ROOT/PRIVATE/RPC/RUNTIME/MTRT" \
    "$NT_ROOT/PRIVATE/WINDOWS/SCREG/WINREG" \
    "$NT_ROOT/PRIVATE/WINDOWS/SCREG/SC" \
    "$NT_ROOT/PRIVATE/EVENTLOG" \
    "$NT_ROOT/PRIVATE/LSA" \
    "$NT_ROOT/PRIVATE/NEWSAM"; do
    find "$stub_dir" -maxdepth 2 \( -name '*_c.c' -o -name '*_s.c' \
        -o -name '*rpc.h' -o -name '*rpc_c.h' \) -delete 2>/dev/null
done

# Build products in PUBLIC/SDK/LIB/I386 that we generate
for f in ntoskrnl.lib ntoskrnl.exp hal.exp tmp.lib tmp.exp \
         ntdll.dll ntdll.exp \
         kernel32.dll kernel32.exp \
         advapi32.dll advapi32.exp \
         rpcrt4.dll rpcrt4.exp rpcrt4.lib \
         samlib.dll samlib.exp samlib.lib \
         samsrv.dll samsrv.exp samsrv.lib \
         lsasrv.dll lsasrv.exp lsasrv.lib \
         csrsrv.dll csrsrv.exp csrsrv.lib \
         basesrv.dll basesrv.exp basesrv.lib \
         atdisk.sys null.sys fastfat.sys \
         gdisrvl.lib efloat.lib fscaler.lib ttfd.lib bmfd.lib vtfd.lib halftone.lib \
         gdi32.dll gdi32.exp gdi32p.exp gdi32p.lib \
         usersrvl.lib \
         user32.dll user32.exp user32p.exp user32p.lib \
         userexts.dll userexts.exp userexts.lib \
         consrvl.lib \
         conexts.dll conexts.exp conexts.lib \
         winsrv.dll winsrv.exp winsrv.lib \
         lsadll.lib; do
    if [ -f "$NT_ROOT/PUBLIC/SDK/LIB/I386/$f" ]; then
        rm -f "$NT_ROOT/PUBLIC/SDK/LIB/I386/$f"
        echo "  cleaned PUBLIC/SDK/LIB/I386/$f"
    fi
done

# cmd-stub build artifacts (rebuilt on demand by build.sh)
rm -f "$SCRIPT_DIR/cmd-stub/cmd.obj" "$SCRIPT_DIR/cmd-stub/cmd.exe" 2>/dev/null

# wibo-tools/ is auto-provisioned by build.sh; removing it forces
# re-creation on next build (including cmd.exe rebuild).
if [ -d "$SCRIPT_DIR/wibo-tools" ]; then
    rm -rf "$SCRIPT_DIR/wibo-tools"
    echo "  cleaned wibo-tools/"
fi

# Generated boot disk image + EFI artifacts
# USER files generated by listmung from .TPL + .LST
rm -f "$NT_ROOT/PRIVATE/WINDOWS/USER/INC/callback.h" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/INC/csuser.h" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/INC/cscall.h" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/SERVER/dispcf.c" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/SERVER/callcf.c" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/CLIENT/dispcb.c" \
      "$NT_ROOT/PRIVATE/WINDOWS/USER/CLIENT/user32p.def" 2>/dev/null

# Profile-specific disk images (under build/)
for profile in micront headless gui; do
    if [ -d "$(dirname "$SCRIPT_DIR")/build/$profile" ]; then
        rm -rf "$(dirname "$SCRIPT_DIR")/build/$profile"
        echo "  cleaned build/$profile/"
    fi
done

echo "Clean complete."
